# Generated by Django 3.2.9 on 2021-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Fax', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Web', models.CharField(blank=True, max_length=100, null=True)),
                ('Bin', models.CharField(blank=True, max_length=255, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Mrcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Mr_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Doc_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Insured_Name', models.CharField(blank=True, max_length=1500, null=True)),
                ('Insured_Address', models.CharField(blank=True, max_length=1500, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=1500, null=True)),
                ('Bank_Address', models.CharField(blank=True, max_length=1500, null=True)),
                ('Premium', models.CharField(blank=True, max_length=255, null=True)),
                ('Vat', models.CharField(blank=True, max_length=255, null=True)),
                ('Stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('ServiceCharge', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('Mode_Of_Payment', models.CharField(blank=True, max_length=255, null=True)),
                ('inword', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
