# Generated by Django 3.2.9 on 2021-11-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrcreate',
            name='CoIns_Net',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mrcreate',
            name='Other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
