# Generated by Django 3.2.9 on 2021-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20211127_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccovernotem',
            name='Prints',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
